version: '3.2'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.back
    ports:
      - 3000:3000
    command: "npm run start"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.front
    ports:
      - 8080:8080
    command: "npm run start"

  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: jamesnumart@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres