version: "3.9"

services:

  redis:
    container_name: admin-house-redis
    image: redis:7.2.4-alpine
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 10s
    ports:
      - 6379:6379

  redis-commander:
    container_name: admin-house-redis-commander
    hostname: redis-commander
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 10s
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  efr-minio:
    container_name: admin-house-minio
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9900:9000"
      - "9901:9001"
#    volumes:
#      - efr-minio-data:/data
    environment:
      - MINIO_ROOT_USER=numart
      - MINIO_ROOT_PASSWORD=numart
    command: server /data --console-address ":9001"

  efr-minio-create-buckets:
    image: minio/mc
    depends_on:
      - efr-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set efr_minio http://efr-minio:9000 efr Qwerty123!;
      /usr/bin/mc mb efr_minio/documents;
      exit 0;

volumes:
  data:
  efr-minio-data:
