version: '3.2'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.back
    ports:
      - 3000:3000
    command: "npm run start"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.front
    ports:
      - 8080:8080
    command: "npm run start"