version: "3.9"

services:

  redis:
    container_name: admin-house-redis
    image: redis:7.2.4-alpine
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 10s
    ports:
      - 6379:6379

  redis-commander:
    container_name: admin-house-redis-commander
    hostname: redis-commander
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 10s
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  s3-minio:
    container_name: admin-house-minio
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./s3-minio-data:/data
    environment:
      - MINIO_ROOT_USER=numart
      - MINIO_ROOT_PASSWORD=!Numart32
      - MINIO_SERVER_URL=http://localhost:9000
#      - MINIO_SERVER_URL=http://minio.alibaba.hhos.ru:9000
    command: server --console-address ":9001" /data

  s3-minio-create-buckets:
    image: minio/mc
    depends_on:
      - s3-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set my-s3-minio http://s3-minio:9000 numart !Numart32;
      /usr/bin/mc mb my-s3-minio/start-bucket;
      /usr/bin/mc policy set public my-s3-minio/start-bucket;
      exit 0;
      "

volumes:
  data:
  s3-minio-data:
