version: "3.9"

services:

  redis:
    container_name: admin-house-redis
    image: redis:7.2.4-alpine
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 10s
    ports:
      - 6379:6379

  redis-commander:
    container_name: admin-house-redis-commander
    hostname: redis-commander
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 10s
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  data:
