FROM node:20.11.1-alpine

WORKDIR /back

COPY package.json /back

RUN npm config set registry http://registry.npmjs.org/
RUN npm install -g @nestjs/cli
RUN npm install prisma --save-dev
RUN npm install
RUN npx prisma generate

#ENV
#ENV NODE

COPY . .

RUN npm run build

