export const enum CACHE_KEYS {
  ROLE_ALL = 'ROLE_ALL',
  USER_ALL = 'USER_ALL',
  USER_FULL_INFO = 'USER_FULL_INFO',
  WORKSPACE_ALL = 'WORKSPACE_ALL',
  ORGANIZATION_ALL = 'ORGANIZATION_ALL',
  PROJECT_ALL = 'PROJECT_ALL',
  GLOBAL_CATEGORY_ALL = 'GLOBAL_CATEGORY_ALL',
}
