export const enum EntityName {
  ROLE = 'ROLE',
  USER = 'USER',
  HANDBOOK = 'HANDBOOK',
  WORKSPACE = 'WORKSPACE',
  ORGANIZATION = 'ORGANIZATION',
  AUTH = 'AUTH',
  PROJECT = 'PROJECT',
  GLOBAL_CATEGORY = 'GLOBAL_CATEGORY',
}
