export const enum KFI {
  APP_INFO_REPOSITORY = 'APP_INFO_REPOSITORY',
  APP_INFO_SERVICE = 'APP_INFO_SERVICE',

  AUTH_REPOSITORY = 'AUTH_REPOSITORY',
  AUTH_SERVICE = 'AUTH_SERVICE',

  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_SERVICE = 'USER_SERVICE',

  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  ROLE_SERVICE = 'ROLE_SERVICE',

  WORKSPACE_REPOSITORY = 'WORKSPACE_REPOSITORY',
  WORKSPACE_SERVICE = 'WORKSPACE_SERVICE',

  HANDBOOK_REPOSITORY = 'HANDBOOK_REPOSITORY',
  HANDBOOK_SERVICE = 'HANDBOOK_SERVICE',

  ORGANIZATION_REPOSITORY = 'ORGANIZATION_REPOSITORY',
  ORGANIZATION_SERVICE = 'ORGANIZATION_SERVICE',

  PROJECT_REPOSITORY = 'PROJECT_REPOSITORY',
  PROJECT_SERVICE = 'PROJECT_SERVICE',

  GLOBAL_CATEGORY_MATERIAL_REPOSITORY = 'GLOBAL_CATEGORY_REPOSITORY',
  GLOBAL_CATEGORY_MATERIAL_SERVICE = 'GLOBAL_CATEGORY_SERVICE',

  CATEGORY_MATERIAL_REPOSITORY = 'CATEGORY_MATERIAL_REPOSITORY',
  CATEGORY_MATERIAL_SERVICE = 'CATEGORY_MATERIAL_SERVICE',

  FIELD_OF_CATEGORY_MATERIAL_REPOSITORY = 'FIELD_OF_CATEGORY_MATERIAL_REPOSITORY',
  FIELD_OF_CATEGORY_MATERIAL_SERVICE = 'FIELD_OF_CATEGORY_MATERIAL_SERVICE',

  CHARACTERISTICS_MATERIAL_REPOSITORY = 'CHARACTERISTICS_MATERIAL_REPOSITORY',
  CHARACTERISTICS_MATERIAL_SERVICE = 'CHARACTERISTICS_MATERIAL_SERVICE',

  FIELD_VARIANTS_FOR_SELECTOR_FIELD_TYPE_REPOSITORY = 'FIELD_VARIANTS_FOR_SELECTOR_FIELD_TYPE_REPOSITORY',
  FIELD_VARIANTS_FOR_SELECTOR_FIELD_TYPE_SERVICE = 'FIELD_VARIANTS_FOR_SELECTOR_FIELD_TYPE_SERVICE',

  FIELD_TYPE_REPOSITORY = 'FIELD_TYPE_REPOSITORY',
  FIELD_TYPE_SERVICE = 'FIELD_TYPE_SERVICE',

  FIELD_UNIT_MEASUREMENT_REPOSITORY = 'FIELD_UNIT_MEASUREMENT_REPOSITORY',
  FIELD_UNIT_MEASUREMENT_SERVICE = 'FIELD_UNIT_MEASUREMENT_SERVICE',

  RESPONSIBLE_PARTNER_PRODUCER_REPOSITORY = 'RESPONSIBLE_PARTNER_PRODUCER_REPOSITORY',
  RESPONSIBLE_PARTNER_PRODUCER_SERVICE = 'RESPONSIBLE_PARTNER_PRODUCER_SERVICE',

  MATERIAL_REPOSITORY = 'MATERIAL_REPOSITORY',
  MATERIAL_SERVICE = 'MATERIAL_SERVICE',

  PRICE_CHANGING_REPOSITORY = 'PRICE_CHANGING_REPOSITORY',
  PRICE_CHANGING_SERVICE = 'PRICE_CHANGING_SERVICE',

  STATUS_RESOURCE_REPOSITORY = 'STATUS_RESOURCE_REPOSITORY',
  STATUS_RESOURCE_SERVICE = 'STATUS_RESOURCE_SERVICE',

  TECH_LOG_CHANGES_REPOSITORY = 'TECH_LOG_CHANGES_REPOSITORY',
  TECH_LOG_CHANGES_SERVICE = 'TECH_LOG_CHANGES_SERVICE',

  PRISMA_SERVICE = 'PRISMA_SERVICE',
}
