export const enum KEYS_FOR_INJECTION {
  I_USER_REPOSITORY = 'I_USER_REPOSITORY',
  I_USER_SERVICE = 'I_USER_SERVICE',

  I_ROLE_REPOSITORY = 'I_ROLE_REPOSITORY',
  I_ROLE_SERVICE = 'I_ROLE_SERVICE',

  I_AUTH_REPOSITORY = 'I_AUTH_REPOSITORY',
  I_AUTH_SERVICE = 'I_AUTH_SERVICE',

  I_WORKSPACE_REPOSITORY = 'I_WORKSPACE_REPOSITORY',
  I_WORKSPACE_SERVICE = 'I_WORKSPACE_SERVICE',

  I_ORGANIZATION_REPOSITORY = 'I_ORGANIZATION_REPOSITORY',
  I_ORGANIZATION_SERVICE = 'I_ORGANIZATION_SERVICE',

  I_PROJECT_REPOSITORY = 'I_PROJECT_REPOSITORY',
  I_PROJECT_SERVICE = 'I_PROJECT_SERVICE',

  I_HANDBOOK_REPOSITORY = 'I_HANDBOOK_REPOSITORY',
  I_HANDBOOK_SERVICE = 'I_HANDBOOK_SERVICE',

  I_FIELD_REPOSITORY = 'I_FIELD_REPOSITORY',
  I_FIELD_SERVICE = 'I_FIELD_SERVICE',

  I_PRISMA_SERVICE = 'I_PRISMA_SERVICE',
  I_LOGGER = 'I_LOGGER',
}
