name: Build
on:
  push:
    branches: [main]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    needs: [job-back-lint, job-back-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile.back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/admin-house-back:latest
