#3 шаг
#Берем машину GitHub, устанавливаем соединение с VDS по ssh, подтягиваем docker-контейнеры с докерхаба, подтягиваем все изменения с GitHub и разворачиваем все наши контейнеры (в том числе фронт и бэк, которые уже лежат на докерхабе благодаря 1 шагу - build.yml)
#to prod

name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect, pull and restart container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout main && git pull && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin-house-front:latest && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin-house-back:latest && docker compose up -d --no-deps --force-recreate && exit"
      - name: cleanup
        run: rm -rf ~/.ssh

  send-start-deploy-telegram-message:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🏹 Deploy ${{ github.REPOSITORY }} Deployment has started
            commit message: ${{ github.event.head_commit.message }}
            author: ${{ github.event.head_commit.author.name }}
            commit timestamp: ${{ github.event.head_commit.timestamp }}

  send-telegram-message:
    name: Send Telegram message
    needs: [ deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ ${{ github.REPOSITORY }} Build, Deployed Successfully
            image tag: *${{ github.sha }}*
            commit message: ${{ github.event.head_commit.message }}
            author: ${{ github.event.head_commit.author.name }}
            commit timestamp: ${{ github.event.head_commit.timestamp }}

  notify-on-error:
    runs-on: ubuntu-latest
    needs: [ deploy ]
    if: failure()
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Send error notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ ${{ github.REPOSITORY }} One of the jobs has fail
